### ISSUE TITLE
Allow configuration of exception strategy: Stop, retry or Ignore

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/kafka-connect-zeebe#24]
When one message can't be processed, what shall we do with it?
Currently it stops the whole processing, which is a reasonable default with Kafka I think. But we should also allow users to define other strategies.

See https://zeebe-io.slack.com/archives/C6WGNHV2A/p1570112570176400

TODO: Double check how other Kafka Connectors handle this.

**Comment by menski** [comment]
@berndruecker I think this is already build in to kafka connect, see this blog post for more information https://www.confluent.io/blog/kafka-connect-deep-dive-error-handling-dead-letter-queues/

As we merged #25 we should now only throw exceptions on real problems, where the default kafka error handling options make sense.

**Comment by berndruecker** [comment]
Thanks! I will look into it hopefully early next week - this week is traveling...

**Comment by berndruecker** [comment]
Yes - that's a great resource - thanks! That absolutely solves the issue. I add a link in the docs: https://github.com/zeebe-io/kafka-connect-zeebe/commit/01d96245b2555dc087370e7e79ae65d5ca4a0cb6
