### ISSUE TITLE
Build fails when upgrading Zeebe dependency from 0.22.1 to 0.23.1

### ISSUE THREAD

**Issue by Klaus-Nji-sp** [zeebe-io/kafka-connect-zeebe#40]
I just tried rebuilding the project with the new release 0.23.1 release of Zeebe and getting some compilation failures.  There are a couple of compile errors around using plain text and other incompatibilities.  

Would someone please take a look?

**Comment by berndruecker** [comment]
Will be fixed with https://github.com/zeebe-io/kafka-connect-zeebe/issues/46
