### ISSUE TITLE
Updating sample ping-pong process to use FEEL expression in correlation key fails process

### ISSUE THREAD

**Issue by Klaus-Nji-sp** [zeebe-io/kafka-connect-zeebe#41]
Upgrade your Zeebe installation to 0.23.1 and retry the sample ping-pong process.  

Deployment will fail with the following error:

```
Command rejected with code 'CREATE': Expected to deploy new resources, but encountered the following errors:
'kafka-test-process': - Element: Message_19mpeg2 > extensionElements > subscription
    - ERROR: Expected expression but found static value 'key'. An expression must start with '=' (e.g. '=key').
```

However, if you correct the error by adding `= ` in front of the Subscription Correlation Key for the Kafka Sink (From Kafka), the process will no longer execute to completion.  Error encountered by the sink is:

`com.jayway.jsonpath.PathNotFoundException: No results for path: $['variablesAsMap']['key']\n\tat io.zeebe.kafka.connect.sink.ZeebeSinkTask.put(ZeebeSinkTask.java:66)\n\tat org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:538)\n\t... 10 more\nCaused by: com.jayway.jsonpath.PathNotFoundException: No results for path: $['variablesAsMap']['key']\n\tat com.jayway.jsonpath.internal.path.EvaluationContextImpl.getValue(EvaluationContextImpl.java:133)\n\tat com.jayway.jsonpath.JsonPath.read(JsonPath.java:187)\n\tat com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:102)\n\tat io.zeebe.kafka.connect.sink.message.JsonRecordParser.parse(JsonRecordParser.java:56)\n\tat io.zeebe.kafka.connect.sink.ZeebeSinkTask.preparePublishRequest(ZeebeSinkTask.java:95)`

**Comment by Klaus-Nji-sp** [comment]
There is actually no problem.  Underlying issue was double escaping of the payload data when testing this on a mac.  

Here is what works on a mac assuming you are running zbctl on the Zeebe docker image:

docker exec -it zeebe_broker_1  zbctl --insecure create instance --variables '{"name": "pong", "payload": { "foo": "bar"}, "key": 1}' ping-pong

**Comment by berndruecker** [comment]
Will be fixed with https://github.com/zeebe-io/kafka-connect-zeebe/issues/46

**Comment by berndruecker** [comment]
Sorry for the delay!
