### ISSUE TITLE
Publish on Confluent Hub

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/kafka-connect-zeebe#5]
One of our goals is to publish the connector to Confluent Hub. I think we're almost there, but we're missing some things, or some things I'm not sure are complete. Here are the [official guidelines](https://docs.confluent.io/current/connect/managing/confluent-hub/component-archive.html#confluent-hub-component-archive). At the moment, when doing a `mvn package`, it will produce a zip file in the target folder which has the correct archive format, with manifest, logos, doc, JARs, etc. But there are some open issues I think:

1. Logos: are these the Camunda approved ones?
1. Package metadata and description: is the below correct? Who to ask?

```xml
<configuration>
  <title>Kafka Connect Zeebe</title>
  <documentationUrl>https://github.com/zeebe-io/kafka-connect-zeebe/</documentationUrl>
  <description>Write description</description>
  <logo>logos/zeebe.png</logo>

  <supportProviderName>Camunda Services GmbH</supportProviderName>
  <supportSummary>Camunda supports the Zeebe source and sink connectors as a community
    project.
  </supportSummary>
  <supportUrl>https://github.com/zeebe-io/kafka-connect-zeebe/</supportUrl>
  <supportLogo>logos/camunda.png</supportLogo>

  <ownerUsername>zeebe-io</ownerUsername>
  <ownerType>organization</ownerType>
  <ownerName>Camunda Services GmbH</ownerName>
  <ownerUrl>https://zeebe.io/</ownerUrl>
  <ownerLogo>logos/zeebe.png</ownerLogo>

  <!-- TODO later
  <dockerNamespace>camunda</dockerNamespace>
  <dockerName>cp-kafka-connect</dockerName>
  <dockerTag>${project.version}</dockerTag>
  -->

  <componentTypes>
    <componentType>sink</componentType>
    <componentType>source</componentType>
  </componentTypes>

  <tags>
    <tag>Zeebe</tag>
    <tag>zeebe</tag>
    <tag>camunda</tag>
    <tag>Camunda</tag>
    <tag>workflows</tag>
    <tag>orchestration</tag>
  </tags>

  <requirements>
    <requirement>Zeebe ${version.zeebe}</requirement>
  </requirements>

  <deliveryGuarantee>
    <deliveryGuarantee>exactlyOnce</deliveryGuarantee>
  </deliveryGuarantee>

  <confluentControlCenterIntegration>true</confluentControlCenterIntegration>
</configuration>
```

1. Licenses: seems most connectors package the licenses of all their dependencies as well, since these get distributed as well. I haven't done this yet, so we probably need to do something there.

**Comment by berndruecker** [comment]
Just for documentation: We are currently in the process of verifying the connector. I am DRI for that.

**Comment by berndruecker** [comment]
It is there: https://www.confluent.io/hub/zeebe-io/kafka-connect-zeebe
