### ISSUE TITLE
Is Zeebe accurate for me?

### ISSUE THREAD

**Issue by coloal** [zeebe-io/kafka-connect-zeebe#52]
Hi, I have a Kafka cluster and a Kafka Connect cluster running on AKS, using Kubernetes and Strimzi. And I wanted that my Kafka Connect cluster were able to recieve and orchestrate a lot of requests of reading RSS feeds. So I want a way of dynamically instantiate Connectors which reads a desired RSS feed and also something that ensures the state of the kafka connectors is the desired one, I mean that if a connector stops working it should be restarted in anyway, or if it were deleted it would be recreated ensuring the desired system state is met. I have been thinking about doing this by making the service, which sends the RSS feeds reading requests, responsible of the Connectors states via the Kafka Connect REST API but lots of doubts arises to me. I do not know if Zeebee could help me in any way on this since after reading the docs I have not understand if it suited me. Thanks!

**Comment by berndruecker** [comment]
Sorry for the late reply. Please ask questions like this via the forum: https://forum.zeebe.io/.
Spontaneously thinks sounds like a use case where you might not want to use the connector, but simply a Zeebe client in the programming language of your choice (which is?) as this gives you much more control over what you are doing.
